### ISSUE TITLE
chrome.identity.removeCachedAuthToken broken

### ISSUE THREAD

**Issue by Ikirys** [MobileChromeApps/cordova-plugin-chrome-apps-identity#4]
chrome.identity.removeCachedAuthToken never seems to finish. Callback function is never called. 
Other chrome identity functions appear to be working (getAuthToken is fine). No related output appears to be in the log file either.

**Comment by Ikirys** [comment]
Turns out it's not broken at all, the docs are just missing information. ChromeIdentity.java runs into an error in the execute method, specifically this line: "callDetails.signOut = args.getBoolean(1);"
Apparently, "signOut" is a required part of the details object that is sent to the method, but none of the documentation reflects that. Adding this field to the details object when making the function call clears up the issue.

Example:
chrome.identity.removeCachedAuthToken({ token: current_token, signOut: true },
                            function() {
                                console.log("Cached token has been removed")
                            });

**Comment by agrieve** [comment]
Thanks for bringing this up. Looks like it was a regression in the most recent version. I've published the fix (`signOut` should be optional)
